version: "3.2"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local

services:
  nginx:
    image: nginx:1.18.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.sh:/run.sh:ro
    command: ["bash", "/run.sh"]
    networks:
      gitea:
        aliases:
          - play-with-go.dev
    ports:
      - "4443:443"
    environment:
      - PLAYWITHGODEV_CERT_FILE
      - PLAYWITHGODEV_KEY_FILE

  gitea:
    image: gitea/gitea:1.12.1
    networks:
      gitea:
        aliases:
          - giteaserver
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - PLAYWITHGODEV_GITHUB_USER
      - PLAYWITHGODEV_GITHUB_PAT
    volumes:
      - ./app.ini:/data/gitea/conf/app.ini:ro
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
