version: "3.2"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local

services:
  gitea:
    image: gitea/gitea:1.14.5
    networks:
      gitea:
        aliases:
          - random.com
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./docker/gitea/app.ini:/data/gitea/conf/app.ini:ro
      - gitea:/data

  cmd_gitea:
    build:
      context: .
      dockerfile: ./docker/cmd_gitea/Dockerfile
    networks:
      - gitea
    environment:
      - PLAYWITHGODEV_CONTRIBUTOR_USER
      - PLAYWITHGODEV_CONTRIBUTOR_PASSWORD
      - GITEA_ROOT_URL
    command: ["/runbin/gitea", "serve"]

