package gitea

type NewUser struct {
	Repos []Repo
}

type Repo struct {
	// Var is the variable name to use for the repository
	Var string

	// Pattern specifies the name pattern of the repository. The respository
	// name is generated by taking Pattern and applying a random string to the
	// end. If Pattern includes a "*", the random string replaces the last "*"
	Pattern string
}
