// Copyright 2020 The play-with-go.dev Authors. All rights reserved.  Use of
// this source code is governed by a BSD-style license that can be found in the
// LICENSE file.

package gitea

//go:generate go run cuelang.org/go/cmd/cue get go --local

type NewUser struct {
	Repos []Repo
}

type Repo struct {
	// Var is the variable name to use for the repository
	Var string

	// Pattern specifies the name pattern of the repository. The respository
	// name is generated by taking Pattern and applying a random string to the
	// end. If Pattern includes a "*", the random string replaces the last "*"
	Pattern string
}
