package ci

import (
	"tool/exec"
	"tool/file"
	"encoding/yaml"
	"strings"
)

command: gengithub: {
	modRoot: exec.Run & {
		cmd:    "go list -m -f {{.Dir}}"
		stdout: string
	}
	for w in workflows {
		write: file.Create & {
			filename: "\(strings.TrimSpace(modRoot.stdout))/.github/workflows/\(w.file)"
			contents: """
				# Generated by ci_tool.cue; do not edit

				\(yaml.Marshal(w.schema))
				"""
		}
	}
}
